version: '3.9'

services:
  postgres:
    image: postgres:16
    container_name: banking_postgres

    environment:
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: 1907
      POSTGRES_DB: banking_db

    ports:
      - "5433:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  adminer:
    image: adminer
    container_name: banking_adminer
    ports:
      - "8080:8080"
    
    depends_on:
      - postgres
  
  python-etl:
    build: .
    container_name: banking_python_etl

    environment:
      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: 1907
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: banking_db
    
    depends_on:
      - postgres

  airflow-init:
    image: apache/airflow:2.10.0
    container_name: airflow_init

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://bank_user:1907@postgres:5432/banking_db

      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: 1907
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: banking_db

    command: >
      bash -c "
      airflow db migrate &&
      airflow users create
      --username admin
      --password admin
      --firstname Admin
      --lastname User
      --role Admin
      --email admin@example.com
      "

    depends_on:
      - postgres

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs/airflow:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - .:/opt/airflow/project

  airflow-webserver:
    image: apache/airflow:2.10.0
    container_name: airflow_webserver
    restart: always

    ports:
      - "8081:8080"

    environment:
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://bank_user:1907@postgres:5432/banking_db

      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: 1907
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: banking_db

    command: webserver

    depends_on:
      - airflow-init

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs/airflow:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - .:/opt/airflow/project

  airflow-scheduler:
    image: apache/airflow:2.10.0
    container_name: airflow_scheduler
    restart: always

    environment:
      APP_ENV: docker
      AIRFLOW__CORE__EXECUTOR: LocalExecutor
      AIRFLOW__DATABASE__SQL_ALCHEMY_CONN: postgresql+psycopg2://bank_user:1907@postgres:5432/banking_db

      POSTGRES_USER: bank_user
      POSTGRES_PASSWORD: 1907
      POSTGRES_HOST: postgres
      POSTGRES_PORT: 5432
      POSTGRES_DB: banking_db

    command: scheduler

    depends_on:
      - airflow-init

    volumes:
      - ./dags:/opt/airflow/dags
      - ./logs/airflow:/opt/airflow/logs
      - ./plugins:/opt/airflow/plugins
      - .:/opt/airflow/project

  superset:
    image: apache/superset:latest
    container_name: banking_superset

    ports:
      - "8088:8088"

    environment:
      SUPERSET_SECRET_KEY: banking_fraud_secret_key

    depends_on:
      - postgres

volumes:
  postgres_data:






